### ISSUE TITLE
有个小问题想请教一下，为什么errorcode.js里面的key值用大写，是根据什么规范吗？key的定义有什么标准吗？

### ISSUE THREAD

**Issue by jaceechan** [eggjs-community/egg-bizerror#3]

**Comment by beliefgp** [comment]
一般这种异常的 code 约定的都是大写。

**Comment by jaceechan** [comment]
因为报错的时候全大写的话，报错内容如下，name那里前面是全大写，后面拼的是Error，整体不一致，所以在想用大写的驼峰式会不会更好？
![image](https://user-images.githubusercontent.com/10494114/69208113-5d30e080-0b8d-11ea-9c8a-6738fe030779.png)

**Comment by beliefgp** [comment]
这个 name 是 [egg-logger](https://github.com/eggjs/egg-logger/blob/0cbbe47efb10897ac55a892bc670d3924a1ddfb5/lib/utils.js#L137) 里进行的处理。

目前阿里这边的风格这种 code 一般都是这种模式，这个主要看你们内部的规范约定吧。

**Comment by jaceechan** [comment]
好的，明白，感谢你的回复，谢谢
